name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Trigger deployment on the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Build and Export Static Files
        run: |
          npm run build
          npm run export  # Export a static build to the 'out/' directory

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: out   # 'out' is the directory with static content
          production-deploy: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
